git-topic-start

diff --git a/git/scripts/git-topic-start b/git/scripts/git-topic-start
--- a/git/scripts/git-topic-start
+++ b/git/scripts/git-topic-start
@@ -8,9 +8,31 @@ dependency git-verify-initial-commit
 
 function git-topic-start() {
   name=$1
-  head=${2:-HEAD}
+  parentHead=${2:-HEAD}
 
-  git-verify-initial-commit $head
+  git-verify-initial-commit $parentHead
+
+  parentCommit=$($git rev-parse $parentHead)
+
+  branchCount=$($git show-ref --heads | grep $parentCommit | wc -l)
+
+  if [ $branchCount = '0' ]; then
+    $git branch $name $parentCommit || exit 1
+    echo "Started topic \`$name' at $parentCommit"
+
+  elif [ $branchCount = '1' ]; then
+    treeID=$($git show --format=%T $parentCommit)
+
+    emptyCommit=$($git commit-tree $treeID -p $parentCommit < /dev/null)
+
+    $git branch $name $emptyCommit || exit 1
+    echo "Started topic \`$name' at $emptyCommit"
+
+  else
+    exec >&2
+
+    echo "Error: topic parent at $parentHead would be ambiguous (Branch Count: $branchCount)"
+  fi
 }
 
 export git-topic-start $@
diff --git a/git/scripts/git-verify-initial-commit b/git/scripts/git-verify-initial-commit
--- a/git/scripts/git-verify-initial-commit
+++ b/git/scripts/git-verify-initial-commit
@@ -5,14 +5,12 @@ set -eu
 source $(dirname $BASH_SOURCE)/git-functions.bash
 
 function git-verify-initial-commit() {
-  head=${1:-master}
+  ref=${1:-HEAD}
 
-  if $git show-ref --heads --head | grep -q $head; then
-    $git rev-list --max-parents=0 --quiet $head
-  else
+  if ! $git rev-parse --quiet HEAD 2>/dev/null >&2; then
     exec >&2
 
-    echo "Error: \`$head' is not a branch (has an initial commit been added yet?)"
+    echo "Error: \`$ref' is not a reference (has an initial commit been added yet?)"
 
     exit 1
   fi
